In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=pd.read_csv("/diabetes.csv")
a

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1

In [ ]:
print(a.info)

<bound method DataFrame.info of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
762            9       89             62              0        0  22.5
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
762                     0.142   33        0
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1

[767 rows x 9 columns]>

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
b = pd.DataFrame(scaler.fit_transform(a))
b

,0,1,2,3,4,5,6,7,8
0,0.638727,0.847055,0.149604,0.907789,-0.693559,0.203622,0.467638,1.424637,1.364529
1,-0.845829,-1.124361,-0.160381,0.531560,-0.693559,-0.684258,-0.365494,-0.191778,-0.732853
2,1.232549,1.942286,-0.263709,-1.286880,-0.693559,-1.102830,0.603475,-0.106704,1.364529
3,-0.845829,-0.999192,-0.160381,0.155331,0.122357,-0.493998,-0.920915,-1.042523,-0.732853
4,-1.142741,0.502839,-1.503649,0.907789,0.764674,1.408602,5.481522,-0.021629,1.364529
...,...,...,...,...,...,...,...,...,...
762,1.529461,-0.999192,-0.367038,-1.286880,-0.693559,-1.204302,-0.996380,-0.021629,-0.732853
763,1.826372,-0.623684,0.356260,1.722952,0.868833,0.114834,-0.908841,2.530605,-0.732853
764,-0.548918,0.033455,0.046275,0.406151,-0.693559,0.609510,-0.398698,-0.532076,-0.732853
765,0.341816,0.002162,0.149604,0.155331,0.278596,-0.734994,-0.685465,-0.276852,-0.732853
766,-0.845829,0.158624,-0.470366,-1.286880,-0.693559,-0.240318,-0.371531,1.169413,1.364529

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca=PCA(n_components = 3)
pca2=pd.DataFrame(pca.fit_transform(b))
pca2

            0         1         2
0   -1.752733 -1.115273  0.212334
1    1.506308  0.562839 -0.653387
2   -0.643163 -1.926006  2.011050
3    1.585544  1.069463 -0.478124
4   -2.483260  2.358416  2.918079
..        ...       ...       ...
762  1.875470 -1.816145 -0.398381
763 -1.279651 -1.216079 -2.050556
764  0.501411  0.674991 -0.632851
765  0.575281 -0.031328 -0.421843
766  0.178030 -1.319242  1.127890

[767 rows x 3 columns]